# -*- coding: utf-8 -*-
# Generated by Django 1.9.dev20150831121505 on 2015-09-01 06:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('value', models.BinaryField()),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(blank=True)),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('_key', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^(0x)?(([a-fA-F0-9]{8})|([a-fA-F0-9]{16})|([a-fA-F0-9]{40}))$', 32), 'Enter a valid PGP/GPG key id with either 8, 16 or 40 characters and an optional 0x prefix.', 'invalid')])),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Keys',
                'verbose_name': 'Key',
            },
        ),
        migrations.AlterUniqueTogether(
            name='key',
            unique_together=set([('owner', '_key')]),
        ),
    ]
